version: '3.5'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: social
    ports:
      - 5432:5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d social" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - social_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@example.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - social_net

  users:
    build: .
    container_name: users
    ports:
      - 8080:8088
    networks:
      - social_net
    depends_on:
      - postgres


volumes:
  postgres_vol:

networks:
  social_net:
      driver: bridge
